config/routes.rb
Rails.application.routes.draw do
  resources :assignments, only: [:index, :show]
  devise_for :users, controllers: {
    sessions: 'user/sessions'
  }

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  #resources :students
 
  get 'home/index'
  
  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/assignment.rb
class Assignment < ApplicationRecord
end

app/controllers/assignments_controller.rb
class AssignmentsController < InheritedResources::Base
  layout 'student'

  def show
    @assignment = Assignment.find(params[:id])
    @user = current_user.id
    # respond_to do |format| 
    # format.html 
    # format.css { render :text => @stylesheet.code, :content_type => "text/css" } 
    # end 
  end


  private

    def assignment_params
      params.require(:assignment).permit(:topic, :content)
    end
end

app/helpers/assignments_helper.rb
module AssignmentsHelper
end

app/views/assignments/_form.html.erb
<%= form_with(model: assignment, local: true) do |form| %>
  <% if assignment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(assignment.errors.count, "error") %> prohibited this assignment from being saved:</h2>

      <ul>
      <% assignment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :topic %>
    <%= form.text_field :topic, id: :assignment_topic %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content, id: :assignment_content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/assignments/edit.html.erb
<h1>Editing Assignment</h1>

<%= render 'form', assignment: @assignment %>

<%= link_to 'Show', @assignment %> |
<%= link_to 'Back', assignments_path %>

app/views/assignments/index.html.erb
<div class="jumbotron">
  <h1 class="display-4 text-center">Assignments</h1>
  <hr class="my-4">
 
</div>
<div class="container">
  <div class="list-group">
    <% @assignments.each do |assignment| %>
      <%= link_to (assignment.topic),assignment, class: "list-group-item list-group-item-action" %>
    <% end %>
  </div>
</div>  

app/views/assignments/new.html.erb
<h1>New Assignment</h1>

<%= render 'form', assignment: @assignment %>

<%= link_to 'Back', assignments_path %>

app/views/assignments/show.html.erb
<div class="jumbotron">
  <h1 class="display-4 text-center text-uppercase"><%= @assignment.topic %></h1>
  <hr class="my-4">
  <div class="detail1-button hidden-xs" ><button id="pdf_link"  class="btn btn-primary detail-button"><%= link_to "Download PDF", assignment_path(@assignment, :format => "pdf"), id: "export"%></button> 
  </div>
</div>
<section>
  <div class="container">
    <div class="row centered">
      <div class="col-md-8 offset-md-2 conent">
        <%= raw(@assignment.content) %>
      </div>
    </div>
  </div>
</section>